export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  EXAM_MANAGER = 'EXAM_MANAGER',
  QUESTION_MODERATOR = 'QUESTION_MODERATOR',
  PROCTOR = 'PROCTOR',
  EVALUATOR = 'EVALUATOR',
  CANDIDATE = 'CANDIDATE',
  AUDITOR = 'AUDITOR',
}

export enum QuestionType {
  MCQ = 'MCQ',
  MSQ = 'MSQ',
  NUMERICAL = 'NUMERICAL',
  SUBJECTIVE = 'SUBJECTIVE',
  CODING = 'CODING',
  CASE_STUDY = 'CASE_STUDY',
  AUDIO = 'AUDIO',
  VIDEO = 'VIDEO',
}

export enum QuestionDifficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
  EXPERT = 'EXPERT',
}

export enum QuestionStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}

export enum ExamType {
  GOVERNMENT = 'GOVERNMENT',
  UNIVERSITY = 'UNIVERSITY',
  RECRUITMENT = 'RECRUITMENT',
  CERTIFICATION = 'CERTIFICATION',
  ONLINE_ASSESSMENT = 'ONLINE_ASSESSMENT',
  CODING = 'CODING',
}

export enum ExamStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum SessionStatus {
  WAITING = 'WAITING',
  IDENTITY_VERIFICATION = 'IDENTITY_VERIFICATION',
  IN_PROGRESS = 'IN_PROGRESS',
  PAUSED = 'PAUSED',
  SUBMITTED = 'SUBMITTED',
  AUTO_SUBMITTED = 'AUTO_SUBMITTED',
  TERMINATED = 'TERMINATED',
  EXPIRED = 'EXPIRED',
}

export enum KycStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum ProctoringEventType {
  NO_FACE = 'NO_FACE',
  MULTIPLE_FACES = 'MULTIPLE_FACES',
  FACE_MISMATCH = 'FACE_MISMATCH',
  LOOKING_AWAY = 'LOOKING_AWAY',
  HEAD_TURNED = 'HEAD_TURNED',
  PHONE_DETECTED = 'PHONE_DETECTED',
  AUDIO_ANOMALY = 'AUDIO_ANOMALY',
  TAB_SWITCH = 'TAB_SWITCH',
  WINDOW_BLUR = 'WINDOW_BLUR',
  COPY_ATTEMPT = 'COPY_ATTEMPT',
  PASTE_ATTEMPT = 'PASTE_ATTEMPT',
  RIGHT_CLICK = 'RIGHT_CLICK',
  DEVTOOLS = 'DEVTOOLS',
  PRINT_ATTEMPT = 'PRINT_ATTEMPT',
  SCREEN_CAPTURE = 'SCREEN_CAPTURE',
  FULLSCREEN_EXIT = 'FULLSCREEN_EXIT',
  VPN_DETECTED = 'VPN_DETECTED',
  VM_DETECTED = 'VM_DETECTED',
}

export enum ViolationSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum EvaluationStatus {
  PENDING = 'PENDING',
  AUTO_EVALUATED = 'AUTO_EVALUATED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  EVALUATED = 'EVALUATED',
  PUBLISHED = 'PUBLISHED',
}

export enum TenantIsolationMode {
  SCHEMA = 'SCHEMA',
  DATABASE = 'DATABASE',
  ROW_LEVEL = 'ROW_LEVEL',
}

export enum CodingLanguage {
  JAVA = 'java',
  PYTHON = 'python',
  JAVASCRIPT = 'javascript',
  CPP = 'cpp',
  CSHARP = 'csharp',
  GO = 'go',
}
